controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    omi_drive:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type:joint_state_broadcaser/JointStateBroadcaster

diff_cont:
  ros__parameters:

  publish_rate: 50.0

  base_frame_id: base_link

  left_wheel_names: ['Left_Front_wheel_joint','left_Rear_wheel_joint']
  right_wheel_names: ['Right_Front_wheel_joint','Right_Rear_wheel_joint']
  wheel_separation: 0.35 #check
  wheel_radius: #check

  use_stamped_vel: false #check this documentation